#!/bin/sh
set -e
ID=$(grep '^ID=' /etc/os-release | cut -d= -f2 | tr -d '"')
cd suckless
sudo ./all
cd ..
mkdir -p ~/Pictures/Wallpapers/
cp -f wallpaper.png ~/Pictures/Wallpapers/
cp -f .xinitrc .xprofile ~/
mkdir -p ~/.config/
cp -r gtk-3.0 gtk-4.0 nvim tmux ~/.config/
