local color00 = "#161616"
local color01 = "#262626"
local color02 = "#393939"
local color03 = "#525252"
local color04 = "#d0d0d0"
local color05 = "#f2f2f2"
local color06 = "#ffffff"
local color07 = "#08bdba"
local color08 = "#3ddbd9"
local color09 = "#78a9ff"
local color10 = "#ee5396"
local color11 = "#33b1ff"
local color12 = "#ff7eb6"
local color13 = "#42be65"
local color14 = "#be95ff"
local color15 = "#82cfff"

vis.lexers.STYLE_DEFAULT = "fore:" .. color04 .. ",back:" .. color00
vis.lexers.STYLE_NOTHING = vis.lexers.STYLE_DEFAULT
vis.lexers.STYLE_ATTRIBUTE = "fore:" .. color15
vis.lexers.STYLE_CLASS = "fore:" .. color09
vis.lexers.STYLE_COMMENT = "fore:" .. color03
vis.lexers.STYLE_CONSTANT = vis.lexers.STYLE_DEFAULT
vis.lexers.STYLE_DEFINITION = "fore:" .. color09
vis.lexers.STYLE_ERROR = "fore:" .. color10 .. ",back:" .. color01
vis.lexers.STYLE_FUNCTION = "fore:" .. color12 .. ",bold"
vis.lexers.STYLE_HEADING = "fore:" .. color15 .. ",bold"
vis.lexers.STYLE_KEYWORD = "fore:" .. color09
vis.lexers.STYLE_LABEL = "fore:" .. color11
vis.lexers.STYLE_NUMBER = "fore:" .. color15
vis.lexers.STYLE_OPERATOR = "fore" .. color09
vis.lexers.STYLE_REGEX = "fore:" .. color07
vis.lexers.STYLE_STRING = "fore:" .. color14
vis.lexers.STYLE_PREPROCESSOR = "fore:" .. color09
vis.lexers.STYLE_TAG = "fore:" .. color04
vis.lexers.STYLE_TYPE = "fore:" .. color09
vis.lexers.STYLE_VARIABLE = vis.lexers.STYLE_DEFAULT
vis.lexers.STYLE_WHITESPACE = "fore:" .. color01
vis.lexers.STYLE_EMBEDDED = "back:" .. color01

vis.lexers.STYLE_IDENTIFIER = vis.lexers.STYLE_DEFAULT
vis.lexers.STYLE_LINENUMBER = "fore:" .. color01
vis.lexers.STYLE_LINENUMBER_CURSOR = "fore:" .. color01 .. ",back:" .. color04
vis.lexers.STYLE_CURSOR = "fore:" .. color00 .. ",back:" .. color04
vis.lexers.STYLE_CURSOR_PRIMARY = vis.lexers.STYLE_CURSOR
vis.lexers.STYLE_CURSOR_LINE = "back:" .. color01
vis.lexers.STYLE_COLOR_COLUMN = "back:" .. color01
vis.lexers.STYLE_SELECTION = "back:" .. color02
vis.lexers.STYLE_STATUS = "fore:" .. color04 .. ",back:" .. color00
vis.lexers.STYLE_STATUS_FOCUSED = "fore:" .. color04 .. ",back:" .. color00  
vis.lexers.STYLE_SEPARATOR = vis.lexers.STYLE_COMMENT
vis.lexers.STYLE_BRACKETS = "fore:" .. color08
vis.lexers.STYLE_INFO = "bold"
vis.lexers.STYLE_EOF = "fore:" .. color02

vis.lexers.STYLE_HR = vis.lexers.STYLE_COMMENT
for i = 1,6 do vis.lexers["STYLE_HEADING_H" .. i] = vis.lexers.STYLE_HEADING end
vis.lexers.STYLE_BOLD = "bold"
vis.lexers.STYLE_ITALIC = "italics"
vis.lexers.STYLE_LIST = vis.lexers.STYLE_KEYWORD
vis.lexers.STYLE_LINK = vis.lexers.STYLE_KEYWORD
vis.lexers.STYLE_REFERENCE = vis.lexers.STYLE_KEYWORD
vis.lexers.STYLE_CODE = vis.lexers.STYLE_EMBEDDED
