[window]
decorations = "Full"
decorations_theme_variant = "Dark"
padding = { x = 16, y = 16 }
dynamic_padding = false

[font]
size = 14.0

[font.normal]
family = "Iosevka Nerd Font"

[font.bold]
family = "Iosevka Nerd Font"

[font.italic]
family = "Iosevka Nerd Font"

[font.bold_italic]
family = "Iosevka Nerd Font"

[general]
import = ["~/.cache/wal/colors-alacritty.toml"]

[scrolling]
history = 10000
multiplier = 3

[keyboard]
bindings = [
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" },
  { key = "Minus", mods = "Control|Shift", action = "DecreaseFontSize" },
  { key = "Equals", mods = "Control|Shift", action = "IncreaseFontSize" }
]

[env]
TERM = "xterm-256color"

#[[keyboard.bindings]]
#key = "Return"
#mods = "Shift"
#chars = "\u001B\r"
