set expandtab
set smartindent
set tabstop=2
set shiftwidth=2
set nu!
set rnu
set cursorline
set fillchars=eob:\ 
set laststatus=3
set mouse=a
set clipboard=unnamedplus
set noshowmode
set noshowcmd
set shortmess+=F
